### PR TITLE
Use "go get" to install ethr

### PR DESCRIPTION
**Pull request by mingrammer**
We don't need to clone and build the ethr manually.

Just run `go get github.com/Microsoft/ethr` to install the ethr.

### CODE REVIEW

**Comment by pgmsft** [comment]
Does this builds it also or just downloads? Also which folder it downloads? This is my first golang project so not sure of all options and want to make sure we have detailed instructions for developers who might be new to golang like me.

**Comment by mingrammer** [comment]
You can see the details of `go get` command with `go help get`. Here is the part of the `go help get`.

```
...
Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.
...
```

> If you want to only download the package, use `go get -d <package>`.

Yes, it will download the `ethr` and deps in `$GOPATH/src/github.com/Microsoft/ethr` (all folders will be created by `go get` command automatically), then install (including build) the `ethr` executable in `$GOPATH/bin`. 

In short, `go get` does

1. clone the project in `$GOPATH/<project path>`.
2. downloads the dependencies and build the project.
3. install the executable in `$GOPATH/bin`.

in the single command.

**Comment by pgmsft** [comment]
Can you please resolve conflicts and resubmit? Then I will merge it.

**Comment by mingrammer** [comment]
Please squash the two commits :)

**Pull request merged**
