### PR TITLE
 Refactor plotter and stats-gathering code

### PR DESCRIPTION
**Pull request by boyan-soubachov**
* Refactor the command line plotting & management code into a package
* Refactor the stats-gathering code into a new package

### CODE REVIEW

**Comment by boyan-soubachov** [comment]
@pgmsft , please excuse the length of this one but it's the smallest unit I could pull out to in order to keep the PR as small as possible. Would appreciate your input :pray:

**Comment by boyan-soubachov** [comment]
@pgmsft : Also, do you think it would be a good idea to switch on travis build checks for any PRs in this repo given that they now all pass? I'm of the opinion that those checks would ensure a good minimum standard of submission and make sure we don't break master.

**Comment by pgmsft** [comment]
@boyan-soubachov Travis build was earlier enabled on the PRs, not sure how it is switched off now. I need to figure out how to enable it again.

**Comment by boyan-soubachov** [comment]
I see. 

I will have a look and try to get it going again but it might require the repo owner/administrator to set some things on GitHub too. Will let you know

**Pull request merged**
